#!/usr/bin/env bash
# generate-tenant-overlay.sh — Generate a Kustomize overlay for a dotCMS tenant.
#
# Produces kustomize/tenants/INSTANCE/kustomization.yaml from tenant parameters.
# Called by tenant-add.sh, or directly by future DB automation.
#
# Usage:
#   TENANT_ID=fakecorp ENV_ID=prod source .env && ./scripts/generate-tenant-overlay.sh
#
# Required:
#   TENANT_ID       — tenant identifier (e.g. fakecorp)
#   ENV_ID          — environment (e.g. prod, staging, dev)
#
# Optional (override defaults):
#   DOTCMS_IMAGE    — full image ref  (default: mirror.gcr.io/dotcms/dotcms:latest)
#   CPU_REQUEST     — CPU request     (default: 500m)
#   MEMORY_REQUEST  — memory request  (default: 2Gi)
#   MEMORY_LIMIT    — memory limit    (default: 3Gi)
#   MIN_REPLICAS    — HPA min         (default: 1)
#   MAX_REPLICAS    — HPA max         (default: 6)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KUSTOMIZE_DIR="${SCRIPT_DIR}/../kustomize"

: "${TENANT_ID:?TENANT_ID must be set}"
: "${ENV_ID:?ENV_ID must be set}"

INSTANCE="${TENANT_ID}-${ENV_ID}"
OVERLAY_DIR="${KUSTOMIZE_DIR}/tenants/${INSTANCE}"

DOTCMS_IMAGE="${DOTCMS_IMAGE:-mirror.gcr.io/dotcms/dotcms:latest}"
CPU_REQUEST="${CPU_REQUEST:-500m}"
MEMORY_REQUEST="${MEMORY_REQUEST:-2Gi}"
MEMORY_LIMIT="${MEMORY_LIMIT:-3Gi}"
MIN_REPLICAS="${MIN_REPLICAS:-1}"
MAX_REPLICAS="${MAX_REPLICAS:-6}"

IMAGE_NAME="${DOTCMS_IMAGE%:*}"
IMAGE_TAG="${DOTCMS_IMAGE##*:}"
[[ "${IMAGE_NAME}" == "${DOTCMS_IMAGE}" ]] && IMAGE_TAG="latest"

mkdir -p "${OVERLAY_DIR}"

cat > "${OVERLAY_DIR}/kustomization.yaml" <<KUSTOMIZE
# Generated by generate-tenant-overlay.sh — do not edit manually
# Tenant: ${TENANT_ID}  Environment: ${ENV_ID}  Instance: ${INSTANCE}
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${TENANT_ID}

resources:
  - ../../dotcms-base

images:
  - name: dotcms/dotcms
    newName: ${IMAGE_NAME}
    newTag: "${IMAGE_TAG}"

patches:
  # ── Rename resources (JSON patch) ──────────────────────────────────────────
  - target: {kind: Deployment, name: dotcms}
    patch: |
      - {op: replace, path: /metadata/name, value: ${INSTANCE}}
  - target: {kind: Service, name: dotcms}
    patch: |
      - {op: replace, path: /metadata/name, value: ${INSTANCE}}
  - target: {kind: Service, name: dotcms-hl}
    patch: |
      - {op: replace, path: /metadata/name, value: ${INSTANCE}-hl}
  - target: {kind: HorizontalPodAutoscaler, name: dotcms}
    patch: |
      - {op: replace, path: /metadata/name, value: ${INSTANCE}}
      - {op: replace, path: /spec/scaleTargetRef/name, value: ${INSTANCE}}
  - target: {kind: PodDisruptionBudget, name: dotcms}
    patch: |
      - {op: replace, path: /metadata/name, value: ${INSTANCE}}

  # ── Instance-specific Deployment config (strategic merge) ──────────────────
  - target: {kind: Deployment, name: dotcms}
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: dotcms
      spec:
        selector:
          matchLabels:
            instance: ${INSTANCE}
        template:
          metadata:
            labels:
              instance: ${INSTANCE}
              botcms.cloud/tenant: ${TENANT_ID}
              botcms.cloud/instance: ${INSTANCE}
          spec:
            containers:
              - name: dotcms
                resources:
                  requests:
                    cpu: "${CPU_REQUEST}"
                    memory: "${MEMORY_REQUEST}"
                  limits:
                    memory: "${MEMORY_LIMIT}"
                env:
                  - name: DOT_DOTCMS_CLUSTER_ID
                    value: ${INSTANCE}
                  - name: DB_BASE_URL
                    value: "jdbc:postgresql://postgres-rw.postgres.svc.cluster.local:5432/${INSTANCE}"
                  - name: DB_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: ${INSTANCE}-postgres
                        key: username
                  - name: DB_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: ${INSTANCE}-postgres
                        key: password
                  - name: DOT_ES_AUTH_BASIC_USER
                    valueFrom:
                      secretKeyRef:
                        name: ${INSTANCE}-os-creds
                        key: username
                  - name: DOT_ES_AUTH_BASIC_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: ${INSTANCE}-os-creds
                        key: password
                volumeMounts:
                  - name: assets
                    mountPath: /data/shared
            volumes:
              - name: assets
                persistentVolumeClaim:
                  claimName: ${INSTANCE}-assets
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                        - key: instance
                          operator: In
                          values: [${INSTANCE}]
                    topologyKey: kubernetes.io/hostname

  # ── Service selectors ───────────────────────────────────────────────────────
  - target: {kind: Service, name: dotcms}
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: dotcms
      spec:
        selector:
          instance: ${INSTANCE}

  - target: {kind: Service, name: dotcms-hl}
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: dotcms-hl
      spec:
        selector:
          instance: ${INSTANCE}

  # ── PDB + HPA tuning ────────────────────────────────────────────────────────
  - target: {kind: PodDisruptionBudget, name: dotcms}
    patch: |-
      apiVersion: policy/v1
      kind: PodDisruptionBudget
      metadata:
        name: dotcms
      spec:
        selector:
          matchLabels:
            instance: ${INSTANCE}

  - target: {kind: HorizontalPodAutoscaler, name: dotcms}
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: dotcms
      spec:
        minReplicas: ${MIN_REPLICAS}
        maxReplicas: ${MAX_REPLICAS}
KUSTOMIZE

echo "Generated: ${OVERLAY_DIR}/kustomization.yaml"
echo "Apply with: kubectl apply -k ${OVERLAY_DIR}"
